name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  php:
    name: Testing
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: '7.4'

    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Setup the PHP ${{ env.PHP_VERSION }} environment on ${{ runner.os }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: phpcs, phpunit
          extensions: imagick, mbstring

      - name: Searching for PHP syntax errors
        run: find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
